name: Run android tests
description: Runs cukeulator android tests

inputs:
  api-level:
    description: Android API level used for the emulator
    required: false
    default: '30'

runs:
  using: composite
  steps:
    - name: run tests
      uses: reactivecircus/android-emulator-runner@e89f39f1abbbd05b1113a29cf4db69e7540cae5a # v2.37.0
      with:
        api-level: ${{ inputs.api-level }}
        arch: x86_64
        emulator-options: -skin 1920x1080 -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        script: ./gradlew :cukeulator:connectedCheck -PdisableAnimations=true
