name: Run android tests
description: Runs cukeulator android tests

inputs:
  api-level:
    description: Android API level used for the emulator
    required: false
    default: '30'

runs:
  using: composite
  steps:
    - name: Gradle cache
      uses: gradle/actions/setup-gradle@v4

    - name: AVD cache
      uses: actions/cache@v5.0.3
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ inputs.api-level }}

    - name: create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@b530d96654c385303d652368551fb075bc2f0b6b # v2.35.0
      with:
        api-level: ${{ inputs.api-level }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."

    - name: run tests
      uses: reactivecircus/android-emulator-runner@b530d96654c385303d652368551fb075bc2f0b6b # v2.35.0
      with:
        api-level: ${{ inputs.api-level }}
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: ./gradlew :cukeulator:connectedCheck -PdisableAnimations=true
