name: Run android tests
description: Runs cukeulator android tests

inputs:
  api-level:
    description: Android API level used for the emulator
    required: false
    default: '35'

runs:
  using: composite
  steps:
    - name: AVD cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 #v5.0.3
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ inputs.api-level }}

    - name: run tests
      uses: reactivecircus/android-emulator-runner@b530d96654c385303d652368551fb075bc2f0b6b # v2.35.0
      with:
        api-level: ${{ inputs.api-level }}
        arch: x86_64
        emulator-options: -skin 1920x1080 -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        script: ./gradlew :cukeulator:connectedCheck -PdisableAnimations=true
