name: Run android tests
description: Runs cukeulator android tests

runs:
  using: composite
  steps:
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        emulator-options: -skin 1920x1080 -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        arch: arm64-v8a
        script: ./gradlew :cukeulator:connectedCheck -PdisableAnimations=true
