name: Release cucumber-android

permissions: { }

on:
  push:
    branches:
      - release/*

jobs:
  publish:
    name: Publish cucumber-android
    runs-on: ubuntu-latest
    environment: Release

    steps:
      - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Check commit has been pushed on origin/main
        run: |
          git fetch --quiet origin main
          git merge-base --is-ancestor HEAD origin/main
      - name: Build the app
        run: ./gradlew build --stacktrace -x lint
      - name: run tests
        uses: ./.github/actions/android-test
      - name: Publish
        uses: ./.github/actions/action-publish-gradle
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus-username: ${{ secrets.SONATYPE_USERNAME }}
          nexus-password: ${{ secrets.SONATYPE_PASSWORD }}
